# Generated by Django 5.1.4 on 2024-12-09 12:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('profile', models.ImageField(upload_to='profile_cm/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='موضوع پیام')),
                ('message', models.TextField(blank=True, verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ارسال')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('directive', models.FileField(upload_to='directive')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('directive', models.FileField(upload_to='directive')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='home')),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('author_image', models.ImageField(upload_to='home')),
                ('job_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('footer_label', models.CharField(max_length=50)),
                ('footer_text', models.CharField(max_length=50)),
                ('footer_label_2', models.CharField(blank=True, max_length=50)),
                ('footer_text_2', models.CharField(blank=True, max_length=50)),
                ('footer_label_3', models.CharField(blank=True, max_length=50)),
                ('footer_text_3', models.CharField(blank=True, max_length=50)),
                ('location', models.URLField(blank=True)),
                ('tel_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slide')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(blank=True, default='10', max_length=3)),
                ('title_step_one', models.CharField(blank=True, max_length=100)),
                ('text_step_one', models.CharField(blank=True, max_length=200)),
                ('title_step_two', models.CharField(blank=True, max_length=100)),
                ('text_step_two', models.CharField(blank=True, max_length=200)),
                ('title_step_three', models.CharField(blank=True, max_length=100)),
                ('text_step_tree', models.CharField(blank=True, max_length=200)),
                ('title_step_four', models.CharField(blank=True, max_length=100)),
                ('text_step_four', models.CharField(blank=True, max_length=200)),
                ('title_step_five', models.CharField(blank=True, max_length=100)),
                ('text_step_five', models.CharField(blank=True, max_length=200)),
                ('title_step_six', models.CharField(blank=True, max_length=100)),
                ('text_step_six', models.CharField(blank=True, max_length=200)),
                ('title_step_seven', models.CharField(blank=True, max_length=100)),
                ('text_step_seven', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('possibility_of_group_registration', models.BooleanField(default=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='Main.field')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('first_name_english', models.CharField(blank=True, max_length=20)),
                ('last_name_english', models.CharField(blank=True, max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=20)),
                ('current_educational_level', models.CharField(blank=True, max_length=20)),
                ('school_name', models.TextField(blank=True)),
                ('name_of_research_center', models.CharField(blank=True, max_length=90)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('national_code', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('emergency_contact_number', models.CharField(default='0000000000', max_length=15)),
                ('fathers_national_code', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=90, null=True)),
                ('address', models.TextField(blank=True)),
                ('parents_phone_number', models.IntegerField(blank=True, default='0000000000')),
                ('year_of_birth', models.CharField(blank=True, max_length=4)),
                ('month_of_birth', models.CharField(blank=True, max_length=25)),
                ('day_of_birth', models.CharField(blank=True, max_length=13)),
                ('number_area', models.IntegerField(blank=True, default=1)),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('registration_type', models.CharField(blank=True, choices=[('انفرادی', 'انفرادی'), ('تیمی', 'تیمی')], default='انفرادی', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions_set', to='auth.permission')),
                ('leagues', models.ManyToManyField(to='Main.league', verbose_name='League')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
