# Generated by Django 5.1.4 on 2024-12-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_field_cost_league_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='cost',
        ),
    ]
