# Generated by Django 5.1.3 on 2024-11-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='League',
            new_name='Field',
        ),
    ]
