# Generated by Django 5.1.3 on 2024-11-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_rename_league_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='possibility_of_group_registration',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tendency',
            name='possibility_of_group_registration',
            field=models.BooleanField(default=True),
        ),
    ]
