# Generated by Django 5.1.3 on 2024-11-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_customuser_registration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('1', 'انفرادی'), ('2', 'تیمی')], default='انفرادی', max_length=20),
        ),
    ]
