# Generated by Django 5.1.3 on 2024-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_customuser_registration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('انفرادی', 'انفرادی'), ('تیمی', 'تیمی')], default='انفرادی', max_length=20),
        ),
    ]
