# Generated by Django 5.1.3 on 2024-11-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_customuser_registration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
