# Generated by Django 5.1.3 on 2024-11-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_studentdashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdashboard',
            name='teacher',
            field=models.CharField(blank=True, default='10', max_length=3),
        ),
    ]
