# Generated by Django 5.1.3 on 2024-11-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_studentdashboard_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tendency',
            new_name='League',
        ),
    ]
