# Generated by Django 5.1.3 on 2024-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_rename_tendency_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='leagues',
            field=models.ManyToManyField(to='Main.league', verbose_name='League'),
        ),
    ]
