# Generated by Django 5.1.3 on 2024-11-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_alter_customuser_leagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdashboard',
            name='text_step_five',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='text_step_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='text_step_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='text_step_seven',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='text_step_six',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='text_step_tree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='text_step_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='title_step_five',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='title_step_four',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='title_step_one',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='title_step_seven',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='title_step_six',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='title_step_three',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='title_step_two',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
