# Generated by Django 5.1.3 on 2024-11-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_studentdashboard_text_step_five_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('profile', models.ImageField(upload_to='profile_cm/')),
            ],
        ),
    ]
