# Generated by Django 5.1.3 on 2024-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_contactusform_alter_league_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusform',
            name='text',
        ),
        migrations.RemoveField(
            model_name='contactusform',
            name='title',
        ),
        migrations.AddField(
            model_name='contactusform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AddField(
            model_name='contactusform',
            name='message',
            field=models.TextField(blank=True, verbose_name='متن پیام'),
        ),
        migrations.AddField(
            model_name='contactusform',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='موضوع پیام'),
        ),
        migrations.AlterField(
            model_name='contactusform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
    ]
