# Generated by Django 5.1.3 on 2024-12-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_remove_contactusform_text_remove_contactusform_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='cost',
        ),
    ]
