# Generated by Django 5.1.4 on 2024-12-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تیم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to='Main.customuser', verbose_name='سرگروه')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.league', verbose_name='لیگ')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='Main.customuser', verbose_name='اعضا')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال دعوت\u200cنامه')),
                ('accepted', models.BooleanField(default=False, verbose_name='پذیرفته شده')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='Main.customuser', verbose_name='کاربر دعوت\u200cشده')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='Main.customuser', verbose_name='دعوت\u200cکننده')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.team', verbose_name='تیم')),
            ],
        ),
    ]
