# Generated by Django 5.1.3 on 2024-12-02 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال دعوت\u200cنامه')),
                ('accepted', models.BooleanField(default=False, verbose_name='پذیرفته شده')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر دعوت\u200cشده')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cکننده')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.team', verbose_name='تیم')),
            ],
        ),
    ]
